---
- name: Configure application
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    application: ryanair
    repository_url: git@github.com:TomaszMolenda/ryanair.git
    repository_path: "/srv/{{ application }}"
    ansible_ssh_extra_args: '-o ForwardAgent=yes'

  tasks:
    - name: Install packages
      apt: 
        update_cache: yes
        state: present
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - python-pip
          - nginx
          - python-flask
          - python3-venv

    - name: Clone repository
      git:
        repo: "{{ repository_url }}"
        dest: "{{ repository_path }}"
        accept_hostkey: yes

    - name: Install requirements in virtualenv
      pip:
        requirements: "{{ repository_path }}/requirements.txt"
        virtualenv: "{{ repository_path }}/{{ application }}env"
        virtualenv_command: "/usr/bin/python3 -m venv"
        virtualenv_site_packages: true

    - name: Ansible copy file to remote server
      copy:
        src: "/home/tomo/PycharmProjects/ryanair/ryanair-a33cd-firebase-adminsdk-jd0w3-595816bfc2.json"
        dest: "{{ repository_path }}/ryanair-a33cd-firebase-adminsdk-jd0w3-595816bfc2.json"

    - name: Copy Upstart configuration
      template:
        src: ryanair-service.j2
        dest: "/etc/systemd/system/{{ application }}.service"

    - name: Make sure {{ application }} service is running
      systemd:
        state: started
        daemon_reload: yes
        name: "{{ application }}"

    - name: Make sure our server is running
      service:
        name: "{{ application }}"
        state: started

    - name: Copy Nginx site
      template:
        src: ryanair-nginx.j2
        dest: "/etc/nginx/sites-enabled/{{ application }}"
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service:
        name: nginx
        state: started

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
